package com.pharmacy.dto;

import com.pharmacy.entity.Medicine;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class MedicineResponse {

    // Medicine ID generated by the database
    private Long id;

    private String medicineName;
    private String genericName;
    private String category;
    private String supplier;
    private String batchNumber;
    private Integer quantity;
    private BigDecimal unitPrice;
    private LocalDate expiryDate;
    private Integer reorderLevel;

    // Created and updated timestamps
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;


    // Empty constructor
    public MedicineResponse() {
    }


    /*
     * Constructor used to convert:
     *
     * Medicine Entity
     *        ↓
     * MedicineResponse DTO
     *
     * This is why MedicineResponse::new
     * in MedicineService will work.
     */
    public MedicineResponse(Medicine medicine) {

        this.id = medicine.getId();

        this.medicineName = medicine.getMedicineName();

        this.genericName = medicine.getGenericName();

        this.category = medicine.getCategory();

        this.supplier = medicine.getSupplier();

        this.batchNumber = medicine.getBatchNumber();

        this.quantity = medicine.getQuantity();

        this.unitPrice = medicine.getUnitPrice();

        this.expiryDate = medicine.getExpiryDate();

        this.reorderLevel = medicine.getReorderLevel();

        this.createdAt = medicine.getCreatedAt();

        this.updatedAt = medicine.getUpdatedAt();
    }


    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedicineName() {
        return medicineName;
    }

    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

    public String getGenericName() {
        return genericName;
    }

    public void setGenericName(String genericName) {
        this.genericName = genericName;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    public Integer getReorderLevel() {
        return reorderLevel;
    }

    public void setReorderLevel(Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}